-- GrosOrteil/GrimoireIcons.lua
-- Curated catalogue for the native Grimoire picker. Recent class abilities are
-- identified by spell ID so retail can provide their current texture; the file
-- path remains a dependency-free fallback for unavailable spell data.
local _, ns = ...

local function icon(name, label)
  return {
    name = name,
    label = label,
    type = "file",
    file = "Interface\\Icons\\" .. name,
  }
end

local CLASS = {
  WARRIOR = { label = "Guerrier", fallback = "Ability_Warrior_Charge" },
  PALADIN = { label = "Paladin", fallback = "Spell_Holy_SealOfMight" },
  HUNTER = { label = "Chasseur", fallback = "Ability_Hunter_AimedShot" },
  ROGUE = { label = "Voleur", fallback = "Ability_Rogue_Eviscerate" },
  PRIEST = { label = "Prêtre", fallback = "Spell_Holy_PowerWordShield" },
  DEATHKNIGHT = { label = "Chevalier de la mort", fallback = "Spell_DeathKnight_DeathStrike" },
  SHAMAN = { label = "Chaman", fallback = "Spell_Nature_Lightning" },
  MAGE = { label = "Mage", fallback = "Spell_Fire_Fireball02" },
  WARLOCK = { label = "Démoniste", fallback = "Spell_Shadow_ShadowBolt" },
  MONK = { label = "Moine", fallback = "ability_monk_tigerpalm" },
  DRUID = { label = "Druide", fallback = "Ability_Druid_Maul" },
  DEMONHUNTER = { label = "Chasseur de démons", fallback = "ability_demonhunter_chaosstrike" },
  EVOKER = { label = "Évocateur", fallback = "ability_evoker_livingflame" },
}

local function spell(spellId, label, classKey)
  local classInfo = CLASS[classKey]
  return {
    name = "spell:" .. tostring(spellId),
    label = label,
    type = "file",
    file = "Interface\\Icons\\" .. classInfo.fallback,
    spellId = spellId,
    classKey = classKey,
    classLabel = classInfo.label,
  }
end

local catalog = {
  {
    category = "Combat",
    icons = {
      icon("Ability_Warrior_Charge", "Charge"),
      icon("Ability_Warrior_Cleave", "Enchaînement"),
      icon("Ability_Warrior_BattleShout", "Cri de guerre"),
      icon("Ability_Warrior_Disarm", "Désarmement"),
      icon("Ability_Rogue_Eviscerate", "Attaque précise"),
      icon("Ability_Rogue_BackStab", "Attaque sournoise"),
      icon("Ability_Hunter_AimedShot", "Tir ajusté"),
      icon("Ability_Druid_Maul", "Attaque bestiale"),
      spell(5308, "Exécution", "WARRIOR"),
      spell(6343, "Coup de tonnerre", "WARRIOR"),
      spell(20271, "Jugement", "PALADIN"),
      spell(31884, "Courroux vengeur", "PALADIN"),
      spell(34026, "Ordre de tuer", "HUNTER"),
      spell(185358, "Tir des arcanes", "HUNTER"),
      spell(2098, "Éviscération", "ROGUE"),
      spell(49998, "Frappe de mort", "DEATHKNIGHT"),
      spell(100780, "Paume du tigre", "MONK"),
      spell(8921, "Éclat lunaire", "DRUID"),
      spell(162794, "Frappe du chaos", "DEMONHUNTER"),
      spell(191427, "Métamorphose", "DEMONHUNTER"),
      spell(356995, "Désintégration", "EVOKER"),
      spell(357210, "Souffle profond", "EVOKER"),
      spell(589, "Mot de l'ombre : Douleur", "PRIEST"),
      spell(421, "Chaîne d'éclairs", "SHAMAN"),
    },
  },
  {
    category = "Magie",
    icons = {
      icon("Spell_Fire_Fireball02", "Boule de feu"),
      icon("Spell_Fire_FlameBolt", "Flamme"),
      icon("Spell_Frost_FrostBolt02", "Éclair de givre"),
      icon("Spell_Frost_FrostNova", "Nova de givre"),
      icon("Spell_Arcane_Blink", "Transfert arcanique"),
      icon("Spell_Arcane_Arcane01", "Énergie arcanique"),
      icon("Spell_Nature_Lightning", "Foudre"),
      icon("Spell_Shadow_ShadowBolt", "Ombre"),
      spell(30451, "Déflagration des arcanes", "MAGE"),
      spell(8092, "Attaque mentale", "PRIEST"),
      spell(47540, "Pénitence", "PRIEST"),
      spell(51505, "Explosion de lave", "SHAMAN"),
      spell(20473, "Horion sacré", "PALADIN"),
      spell(47541, "Voile mortel", "DEATHKNIGHT"),
      spell(49184, "Rafale hurlante", "DEATHKNIGHT"),
      spell(78674, "Éruption stellaire", "DRUID"),
      spell(5176, "Colère", "DRUID"),
      spell(117952, "Éclair de jade crépitant", "MONK"),
      spell(198013, "Rayon accablant", "DEMONHUNTER"),
      spell(361469, "Flamme vivante", "EVOKER"),
      spell(357208, "Souffle de feu", "EVOKER"),
      spell(359073, "Éruption d'éternité", "EVOKER"),
      spell(686, "Trait de l'ombre", "WARLOCK"),
      spell(5740, "Pluie de feu", "WARLOCK"),
    },
  },
  {
    category = "Défense",
    icons = {
      icon("Ability_Warrior_ShieldWall", "Mur protecteur"),
      icon("Ability_Warrior_DefensiveStance", "Posture défensive"),
      icon("Spell_Holy_PowerWordShield", "Bouclier sacré"),
      icon("Spell_Holy_DevotionAura", "Aura protectrice"),
      icon("Spell_Frost_FrostArmor02", "Armure de givre"),
      icon("Ability_Druid_Barkskin", "Peau renforcée"),
      icon("INV_Shield_06", "Bouclier rond"),
      icon("INV_Shield_05", "Bouclier lourd"),
      spell(23920, "Renvoi de sort", "WARRIOR"),
      spell(97462, "Cri de ralliement", "WARRIOR"),
      spell(642, "Bouclier divin", "PALADIN"),
      spell(31224, "Cape d'ombre", "ROGUE"),
      spell(45438, "Bloc de glace", "MAGE"),
      spell(48707, "Carapace anti-magie", "DEATHKNIGHT"),
      spell(48792, "Robustesse glaciale", "DEATHKNIGHT"),
      spell(108271, "Transfert astral", "SHAMAN"),
      spell(104773, "Résolution interminable", "WARLOCK"),
      spell(115203, "Boisson fortifiante", "MONK"),
      spell(22812, "Écorce", "DRUID"),
      spell(198589, "Flou", "DEMONHUNTER"),
      spell(196718, "Ténèbres", "DEMONHUNTER"),
      spell(363916, "Écailles d'obsidienne", "EVOKER"),
      spell(186265, "Aspect de la tortue", "HUNTER"),
      spell(47585, "Dispersion", "PRIEST"),
    },
  },
  {
    category = "Soins",
    icons = {
      icon("Spell_Holy_FlashHeal", "Soin rapide"),
      icon("Spell_Holy_GreaterHeal", "Soin puissant"),
      icon("Spell_Holy_Heal", "Soin"),
      icon("Spell_Nature_HealingWaveGreater", "Vague de soins"),
      icon("Spell_Nature_Rejuvenation", "Récupération"),
      icon("Spell_Holy_LayOnHands", "Imposition des mains"),
      icon("INV_Potion_54", "Potion de soins"),
      icon("INV_Misc_Bandage_12", "Bandage"),
      spell(34428, "Ivresse de la victoire", "WARRIOR"),
      spell(19750, "Éclair lumineux", "PALADIN"),
      spell(85673, "Mot de gloire", "PALADIN"),
      spell(109304, "Enthousiasme", "HUNTER"),
      spell(185311, "Fiole cramoisie", "ROGUE"),
      spell(2061, "Soins rapides", "PRIEST"),
      spell(33076, "Prière de guérison", "PRIEST"),
      spell(48743, "Pacte mortel", "DEATHKNIGHT"),
      spell(8004, "Afflux de soins", "SHAMAN"),
      spell(6201, "Création de pierre de soins", "WARLOCK"),
      spell(116670, "Vivifier", "MONK"),
      spell(8936, "Rétablissement", "DRUID"),
      spell(228477, "Division de l'âme", "DEMONHUNTER"),
      spell(363534, "Rembobinage", "EVOKER"),
      spell(360995, "Étreinte verdoyante", "EVOKER"),
      spell(342245, "Altérer le temps", "MAGE"),
    },
  },
  {
    category = "Mouvement",
    icons = {
      icon("Ability_Rogue_Sprint", "Course"),
      icon("Ability_Druid_Dash", "Ruée"),
      icon("Ability_Hunter_Pathfinding", "Pistage"),
      icon("Ability_Mount_BlackPanther", "Monture"),
      icon("Spell_Nature_Swiftness", "Célérité"),
      icon("Spell_Arcane_TeleportStormWind", "Téléportation"),
      icon("Spell_Arcane_PortalStormWind", "Portail"),
      icon("Spell_Nature_WispSplode", "Esprit mobile"),
      spell(6544, "Bond héroïque", "WARRIOR"),
      spell(190784, "Destrier divin", "PALADIN"),
      spell(781, "Désengagement", "HUNTER"),
      spell(36554, "Pas de l'ombre", "ROGUE"),
      spell(73325, "Saut de foi", "PRIEST"),
      spell(48265, "Avancée de la mort", "DEATHKNIGHT"),
      spell(2645, "Loup fantôme", "SHAMAN"),
      spell(1953, "Transfert", "MAGE"),
      spell(111400, "Ruée ardente", "WARLOCK"),
      spell(109132, "Roulade", "MONK"),
      spell(101643, "Transcendance", "MONK"),
      spell(106898, "Ruée rugissante", "DRUID"),
      spell(195072, "Gangreruée", "DEMONHUNTER"),
      spell(358267, "Vol stationnaire", "EVOKER"),
      spell(370665, "Sauvetage", "EVOKER"),
      spell(369536, "Essor", "EVOKER"),
      spell(79206, "Grâce du marcheur des esprits", "SHAMAN"),
    },
  },
  {
    category = "Contrôle",
    icons = {
      icon("Spell_Frost_ChainsOfIce", "Entraves de glace"),
      icon("Spell_Nature_EntanglingRoots", "Enracinement"),
      icon("Spell_Shadow_Possession", "Possession"),
      icon("Spell_Shadow_MindSteal", "Contrôle mental"),
      icon("Ability_Gouge", "Déstabilisation"),
      icon("Ability_Sap", "Assommer"),
      icon("Spell_Frost_FrostShock", "Choc ralentissant"),
      icon("Spell_Shadow_DeathCoil", "Terreur"),
      spell(5246, "Cri d'intimidation", "WARRIOR"),
      spell(853, "Marteau de la justice", "PALADIN"),
      spell(109248, "Tir de lien", "HUNTER"),
      spell(187650, "Piège givrant", "HUNTER"),
      spell(6770, "Assommer", "ROGUE"),
      spell(408, "Aiguillon perfide", "ROGUE"),
      spell(8122, "Cri psychique", "PRIEST"),
      spell(49576, "Poigne de la mort", "DEATHKNIGHT"),
      spell(108194, "Asphyxier", "DEATHKNIGHT"),
      spell(192058, "Totem condensateur", "SHAMAN"),
      spell(51514, "Maléfice", "SHAMAN"),
      spell(2139, "Contresort", "MAGE"),
      spell(118, "Métamorphose", "MAGE"),
      spell(5782, "Peur", "WARLOCK"),
      spell(6789, "Voile de mort", "WARLOCK"),
      spell(116844, "Anneau de paix", "MONK"),
      spell(115078, "Paralysie", "MONK"),
      spell(33786, "Cyclone", "DRUID"),
      spell(217832, "Emprisonnement", "DEMONHUNTER"),
      spell(358385, "Éboulement", "EVOKER"),
    },
  },
  {
    category = "Utilitaire",
    icons = {
      icon("Ability_Spy", "Observation"),
      icon("Spell_Nature_InvisibilityTotem", "Invisibilité"),
      icon("INV_Misc_Key_03", "Clé"),
      icon("INV_Misc_Book_09", "Connaissance"),
      icon("INV_Misc_Rune_01", "Rune"),
      icon("INV_Misc_QuestionMark", "Mystère"),
      icon("Spell_Holy_DivineIntervention", "Intervention"),
      icon("Spell_Nature_StoneClawTotem", "Totem"),
      spell(6673, "Cri de guerre", "WARRIOR"),
      spell(1044, "Bénédiction de liberté", "PALADIN"),
      spell(5384, "Feindre la mort", "HUNTER"),
      spell(34477, "Détournement", "HUNTER"),
      spell(1856, "Disparition", "ROGUE"),
      spell(21562, "Mot de pouvoir : Robustesse", "PRIEST"),
      spell(42650, "Armée des morts", "DEATHKNIGHT"),
      spell(2825, "Furie sanguinaire", "SHAMAN"),
      spell(1459, "Intelligence des arcanes", "MAGE"),
      spell(111771, "Porte des démons", "WARLOCK"),
      spell(113746, "Toucher mystique", "MONK"),
      spell(1126, "Marque du fauve", "DRUID"),
      spell(188501, "Vision spectrale", "DEMONHUNTER"),
      spell(381748, "Bénédiction du Vol draconique bronze", "EVOKER"),
      spell(374968, "Spirale temporelle", "EVOKER"),
    },
  },
  {
    category = "Potions & bandages",
    icons = {
      icon("INV_Potion_01", "Potion bleue I"),
      icon("INV_Potion_02", "Potion bleue II"),
      icon("INV_Potion_03", "Potion violette I"),
      icon("INV_Potion_04", "Potion violette II"),
      icon("INV_Potion_05", "Potion verte I"),
      icon("INV_Potion_06", "Potion verte II"),
      icon("INV_Potion_07", "Potion rouge I"),
      icon("INV_Potion_08", "Potion rouge II"),
      icon("INV_Potion_09", "Potion jaune I"),
      icon("INV_Potion_10", "Potion jaune II"),
      icon("INV_Potion_11", "Potion sombre I"),
      icon("INV_Potion_12", "Potion sombre II"),
      icon("INV_Potion_13", "Potion claire I"),
      icon("INV_Potion_14", "Potion claire II"),
      icon("INV_Potion_15", "Potion alchimique I"),
      icon("INV_Potion_16", "Potion alchimique II"),
      icon("INV_Potion_51", "Potion de soins mineure"),
      icon("INV_Potion_52", "Potion de soins"),
      icon("INV_Potion_53", "Potion de soins supérieure"),
      icon("INV_Potion_55", "Potion de mana mineure"),
      icon("INV_Potion_56", "Potion de mana"),
      icon("INV_Potion_57", "Potion de mana supérieure"),
      icon("INV_Potion_58", "Potion de protection"),
      icon("INV_Potion_59", "Potion de résistance"),
      icon("INV_Potion_60", "Potion de rapidité"),
      icon("INV_Potion_61", "Potion de puissance"),
      icon("INV_Potion_62", "Potion de régénération"),
      icon("INV_Potion_63", "Potion de rage"),
      icon("INV_Potion_64", "Potion de vision"),
      icon("INV_Potion_65", "Potion de camouflage"),
      icon("INV_Potion_66", "Potion de restauration"),
      icon("INV_Misc_Bandage_01", "Bandage en lin"),
      icon("INV_Misc_Bandage_02", "Bandage épais en lin"),
      icon("INV_Misc_Bandage_03", "Bandage en laine"),
      icon("INV_Misc_Bandage_04", "Bandage épais en laine"),
      icon("INV_Misc_Bandage_05", "Bandage en soie"),
      icon("INV_Misc_Bandage_06", "Bandage épais en soie"),
      icon("INV_Misc_Bandage_07", "Bandage en tisse-mage"),
      icon("INV_Misc_Bandage_08", "Bandage épais en tisse-mage"),
      icon("INV_Misc_Bandage_09", "Bandage runique"),
      icon("INV_Misc_Bandage_10", "Bandage runique épais"),
      icon("INV_Misc_Bandage_11", "Bandage de campagne"),
      icon("INV_Misc_Bandage_13", "Bandage de soins"),
      icon("INV_Misc_Bandage_14", "Bandage renforcé"),
      icon("INV_Misc_Bandage_15", "Bandage imprégné"),
      icon("INV_Misc_Bandage_16", "Bandage de maître"),
    },
  },
}

ns.GrimoireIcons = catalog
