-- Run from the addon root: lua tests/run_ui.lua
package.path = "tests/?.lua;" .. package.path
local mocks = require("mocks")
mocks.install()
local frames = require("ui_mocks")
frames.install()
local ns = require("load").load(true)
frames.fire("ADDON_LOADED", "GrosOrteil")
frames.fire("PLAYER_LOGIN")
frames.layout()
for _,err in ipairs(mocks.errorHandlerCalls) do error(err) end
print("UI initialized: " .. #frames.frames .. " regions")
local T = require("framework")
local UI, Core, Theme = ns.UI, ns.Core, ns.Theme
local function find(predicate)
  for _,f in ipairs(frames.frames) do if predicate(f) then return f end end
end
local function button(text)
  return assert(find(function(f) return f._kind=="Button" and f:GetText()==text and f:IsVisible() end), "button missing: "..text)
end
local function noErrors()
  T.assertEq(#mocks.errorHandlerCalls,0,table.concat(mocks.errorHandlerCalls,"\n"))
end
T.describe("Complete UI integration", function()
  T.it("loads the actual TOC and initializes all pages exactly once", function()
    T.assertNotNil(ns.Guard); T.assertNotNil(ns.PercentageHeal)
    T.assertEq(#UI.pages,11)
    local count=0
    for _,tab in ipairs(UI.tabs) do if tab:IsShown() then count=count+1 end end
    T.assertEq(count,5)
    local created=#frames.frames
    ns.UI_Init()
    T.assertEq(#frames.frames,created)
    noErrors()
  end)
  T.it("renders every class and switches all visible player and pet pages", function()
    for _,b in ipairs(UI.classButtons) do
      b:RunScript("OnClick")
      for _,tab in ipairs({1,5,6,7,8}) do
        UI.setTab(tab); T.assertTrue(UI.pages[tab]:IsShown())
        for i,p in ipairs(UI.pages) do if i~=tab then T.assertFalse(p:IsShown()) end end
      end
      T.assertEq(Core.state.classKey,b.classKey)
    end
    Core.SetPetEnabled(true)
    UI.setSidebarSection(2)
    for _,tab in ipairs({9,10,11}) do UI.setTab(tab); T.assertTrue(UI.pages[tab]:IsShown()) end
    UI.setSidebarSection(1); UI.setTab(1)
    noErrors()
  end)
  T.it("commits a numeric edit exactly once on Enter", function()
    Core.ResetToDefaults(); Core.SetHP(100,100)
    local original, calls=Core.SetHP,0
    Core.SetHP=function(...) calls=calls+1; return original(...) end
    UI.inputs.hpCur:SetFocus(); UI.inputs.hpCur:SetText("73")
    UI.inputs.hpCur:RunScript("OnEnterPressed")
    Core.SetHP=original
    T.assertEq(calls,1); T.assertEq(Core.state.hp,73)
    T.assertFalse(UI.inputs.hpCur:HasFocus())
  end)
  T.it("leaves text-edit undo shortcuts with the focused edit box", function()
    UI.inputs.hpCur:SetFocus()
    frames.ctrl=true; frames.mouseOver=UI.frame
    local depth=Core.GetUndoDepth()
    UI.frame:RunScript("OnKeyDown","z")
    T.assertTrue(UI.frame._propagate)
    T.assertEq(Core.GetUndoDepth(),depth)
    frames.ctrl=false; UI.inputs.hpCur:ClearFocus()
  end)
  T.it("keeps the integrated percentage-heal action operational", function()
    Core.SetHP(10,100)
    local value=assert(find(function(f)
      return f._kind=="EditBox" and f._parent and f._parent._parent==UI.lowerBlock and f._parent:GetWidth()==120
    end))
    value:SetText("20")
    button("Pourcentage"):RunScript("OnClick")
    T.assertEq(Core.state.hp,30)
    noErrors()
  end)
  T.it("creates, edits and copies grimoire entries through the real controls", function()
    UI.setTab(7); UI.openGrimoireEditor()
    T.assertTrue(UI.grimoireEditorOpen)
    -- Opening the editor focuses its title field.
    T.assertNotNil(frames.focus)
    frames.focus:SetText("Flamme de contrôle")
    UI.grimoireDamageHealingEdit:SetText("12-24")
    button("Enregistrer"):RunScript("OnClick")
    T.assertFalse(UI.grimoireEditorOpen)
    T.assertEq(#ns.Grimoire.GetTechniques(),1)
    button("Copier"):RunScript("OnClick")
    T.assertTrue(UI.grimoireCopyDialog:IsShown())
    UI.grimoireCopyDialog:Hide()
    button("Modifier"):RunScript("OnClick")
    frames.focus:SetText("Flamme révisée")
    button("Enregistrer"):RunScript("OnClick")
    T.assertEq(ns.Grimoire.GetTechniques()[1].title,"Flamme révisée")
    UI.openGrimoireIconPicker(nil,function() end)
    T.assertTrue(#UI.grimoireIconPicker.buttons>200)
    UI.grimoireIconPicker:Hide(); UI.setTab(1)
    noErrors()
  end)
  T.it("preserves the pet title across window reopen and profile refresh", function()
    Core.SetPetEnabled(true); Core.SetPetName("Compagnon")
    UI.setSidebarSection(2)
    ns.UI_Show(false); ns.UI_Show(true)
    T.assertEq(UI.title:GetText(),"Compagnon")
    UI.setSidebarSection(1)
  end)
  T.it("builds the target popup and displays authoritative health", function()
    mocks.units = {
      player={name="TestPlayer",realm="TestRealm",guid="Player-1-1",isPlayer=true},
      target={name="TargetPlayer",realm="TestRealm",guid="Player-1-2",isPlayer=true},
    }
    ns.TargetPopup.InjectState("TargetPlayer-TestRealm",Core.state)
    ns.TargetPopup:OnTargetChanged()
    T.assertTrue(_G.GrosOrteilTargetPopup:IsShown())
    T.assertEq(UI.hpBar:GetValue(),Core.state.hp/Core.state.maxHp)
    _G.GrosOrteilTargetPopup:Hide(); mocks.units=nil
    noErrors()
  end)
  T.it("cancels stale close animations when reopened, including direct Show", function()
    Theme.SetReducedMotion(false)
    ns.UI_Show(false, true); T.assertTrue(UI.fadeOut:IsPlaying())
    ns.UI_Show(true); frames.finishAnimations()
    T.assertTrue(UI.frame:IsShown()); T.assertTrue(ns.GetDB().ui.shown)
    ns.UI_Show(false, true); UI.frame:Hide(); UI.frame:Show(); frames.finishAnimations()
    T.assertTrue(UI.frame:IsShown())
  end)
  T.it("settles closing windows immediately when reduced motion is enabled", function()
    ns.UI_Show(false, true)
    Theme.SetReducedMotion(true)
    T.assertFalse(UI.frame:IsShown())
    ns.UI_Show(true); UI.setTab(7)
    for _,group in ipairs(frames.animations) do
      if group.region==UI.frame or group.region==UI.pages[7] then T.assertFalse(group:IsPlaying()) end
    end
    UI.setTab(1); Theme.SetReducedMotion(false)
  end)
  T.it("stops resizing when hidden and persists the complete anchor", function()
    local grip=assert(find(function(f)
      return f._parent==UI.frame and f._NormalTexture and tostring(f._NormalTexture:GetTexture()):find("SizeGrabber",1,true)
    end))
    grip:RunScript("OnMouseDown","LeftButton")
    T.assertNotNil(grip:GetScript("OnUpdate"))
    frames.cursorX=frames.cursorX+30; grip:RunScript("OnUpdate")
    UI.frame:Hide()
    T.assertNil(grip:GetScript("OnUpdate"))
    T.assertEq(ns.GetDB().ui.relativePoint,"BOTTOMLEFT")
    ns.UI_Show(true)
    local _,_,relativePoint=UI.frame:GetPoint(1)
    T.assertEq(relativePoint,"BOTTOMLEFT")
    ns.UI_ResetPosition(); T.assertEq(ns.GetDB().ui.relativePoint,"CENTER")
  end)
  T.it("fits the navigation and fixed control rows at minimum window size", function()
    UI.frame:SetSize(760,460); frames.layout()
    T.assertTrue(UI.content:GetWidth()>=500)
    T.assertTrue(UI.tabs[8]:GetBottom()>UI.resetBtn:GetTop())
    T.assertTrue(UI.inputs.hpCur:GetLeft()>=UI.content:GetLeft())
    T.assertTrue(UI.inputs.hpMax:GetRight()<=UI.content:GetRight())
    UI.frame:SetSize(940,580); frames.layout()
  end)
end)
T.describe("Raid panel combat boundaries",function()
  T.it("defers first creation until combat ends",function()
    frames.combat=true; frames.fire("PLAYER_REGEN_DISABLED")
    ns.RaidPanel.Show(); T.assertNil(_G.GrosOrteilRaidPanel)
    frames.combat=false; frames.fire("PLAYER_REGEN_ENABLED"); frames.layout()
    T.assertTrue(_G.GrosOrteilRaidPanel:IsShown())
    noErrors()
  end)
  T.it("retains secure target attributes and defers view changes",function()
    local sec=assert(find(function(f) return f._attrs.type1=="target" end))
    T.assertEq(sec:GetAttribute("*type1"),"target")
    T.assertNotNil(sec:GetAttribute("unit"))
    T.assertNil(sec:GetScript("OnClick"))
    local sf=_G.GrosOrteilRaidPanelScroll
    local originalChild=sf._scrollChild
    local meter=assert(find(function(f) return f._view=="meter" end))
    frames.combat=true; frames.fire("PLAYER_REGEN_DISABLED")
    meter:RunScript("OnClick")
    T.assertEq(sf._scrollChild,originalChild)
    for _,name in ipairs(UISpecialFrames) do T.assertNeq(name,"GrosOrteilRaidPanel") end
    frames.combat=false; frames.fire("PLAYER_REGEN_ENABLED")
    T.assertNeq(sf._scrollChild,originalChild)
    assert(find(function(f) return f._view=="group" end)):RunScript("OnClick")
  end)
  T.it("handles combat beginning during a close animation",function()
    ns.RaidPanel.Hide()
    frames.combat=true; frames.fire("PLAYER_REGEN_DISABLED")
    frames.finishAnimations()
    T.assertTrue(_G.GrosOrteilRaidPanel:IsShown())
    ns.RaidPanel.Show() -- newest intent wins
    frames.combat=false; frames.fire("PLAYER_REGEN_ENABLED"); frames.finishAnimations()
    T.assertTrue(_G.GrosOrteilRaidPanel:IsShown())
    frames.combat=true; frames.fire("PLAYER_REGEN_DISABLED"); ns.RaidPanel.Hide()
    T.assertTrue(_G.GrosOrteilRaidPanel:IsShown())
    frames.combat=false; frames.fire("PLAYER_REGEN_ENABLED"); frames.finishAnimations()
    T.assertFalse(_G.GrosOrteilRaidPanel:IsShown())
  end)
  T.it("stops scale dragging before any protected mutation in combat",function()
    ns.RaidPanel.Show()
    local panel=_G.GrosOrteilRaidPanel
    local grip=assert(find(function(f)
      return f._parent==panel and f._NormalTexture and tostring(f._NormalTexture:GetTexture()):find("SizeGrabber",1,true)
    end))
    grip:RunScript("OnMouseDown","LeftButton")
    frames.combat=true
    grip:RunScript("OnUpdate")
    T.assertNil(grip:GetScript("OnUpdate"))
    frames.fire("PLAYER_REGEN_DISABLED")
    frames.combat=false; frames.fire("PLAYER_REGEN_ENABLED")
    ns.RaidPanel.Hide(); frames.finishAnimations()
  end)
end)
T.describe("Runtime regressions",function()
  T.it("parses both meter counters through all shipped guards",function()
    ns.Comm:OnChatMsgAddon(ns.Comm.PREFIX,"METER_STATE:42:84","PARTY","Peer-TestRealm")
    local totals=ns.MeterSync.Get("Peer-TestRealm")
    T.assertEq(totals.dmg,42); T.assertEq(totals.heal,84)
    ns.MeterSync.Store("Peer-TestRealm",0/0,math.huge)
    totals=ns.MeterSync.Get("Peer-TestRealm")
    T.assertEq(totals.dmg,0); T.assertEq(totals.heal,0)
  end)
  T.it("passes the shipped in-game suite with the UI subscribed",function()
    local ok,pass,fail=ns.Tests.RunAll(false)
    T.assertTrue(ok,"packaged suite failed: "..tostring(fail)); T.assertTrue(pass>=60)
    noErrors()
  end)
  T.it("has no idle update loops after interactions settle",function()
    Theme.SetReducedMotion(true)
    frames.finishAnimations()
    for _,f in ipairs(frames.frames) do T.assertNil(f:GetScript("OnUpdate"),f._name or f._kind) end
    noErrors()
  end)
end)
local ok=T.run({verbose=true})
os.exit(ok and 0 or 1)
