-- Run from the addon root: lua tests/run_ui.lua
package.path = "tests/?.lua;" .. package.path
local mocks = require("mocks")
mocks.install()
local frames = require("ui_mocks")
frames.install()
local savedTheme = arg and arg[1]
local expectedTheme = savedTheme == "legacy" and "legacy" or "slate"
local ns = require("load").load(true, { settings = { theme = savedTheme, reduceMotion = true } })
frames.fire("ADDON_LOADED", "GrosOrteil")
frames.fire("PLAYER_LOGIN")
frames.layout()
for _,err in ipairs(mocks.errorHandlerCalls) do error(err) end
print("UI initialized (" .. expectedTheme .. "): " .. #frames.frames .. " regions")
local T = require("framework")
local UI, Core, Theme = ns.UI, ns.Core, ns.Theme
local function find(predicate)
  for _,f in ipairs(frames.frames) do if predicate(f) then return f end end
end
local function button(text)
  return assert(find(function(f) return f._kind=="Button" and f:GetText()==text and f:IsVisible() end), "button missing: "..text)
end
local function noErrors()
  T.assertEq(#mocks.errorHandlerCalls,0,table.concat(mocks.errorHandlerCalls,"\n"))
end
T.describe("Complete UI integration", function()
  T.it("toggles typing from the main frame and keeps its footer controls apart", function()
    T.assertTrue(ns.Typing.IsEnabled())
    UI.typingButton:RunScript("OnClick")
    T.assertFalse(ns.Typing.IsEnabled())
    T.assertFalse(ns.GetDB().settings.typingIndicators)
    T.assertEq(UI.typingButton:GetText(), "Saisie : masquée")
    UI.typingButton:RunScript("OnClick")
    T.assertTrue(ns.Typing.IsEnabled())
    T.assertEq(UI.typingButton:GetText(), "Saisie : activée")
    frames.layout()
    T.assertTrue(UI.typingButton:GetLeft() > UI.distanceButton:GetRight())
    T.assertTrue(UI.typingButton:GetRight() < UI.frame:GetRight())
    noErrors()
  end)
  T.it("applies the saved theme before building any UI and defaults to slate", function()
    T.assertEq(Theme.GetName(), expectedTheme)
    T.assertEq(Theme.GetSelectedName(), expectedTheme)
    T.assertEq(ns.GetDB().settings.theme, expectedTheme)
    T.assertEq(UI.tabs[UI.TAB_IDS.THEMES]._text:GetText(), "Thèmes")
    T.assertNil(UI.themeButton); T.assertNil(UI.applyThemeButton)
    T.assertEq(UI.title._textColor[1], Theme.Colors.TEXT_TITLE[1])
    T.assertEq(Theme.Colors.BROWN_DEEP[1], expectedTheme == "legacy" and 0.08 or 0.035)
    T.assertNil(UI.motionButton)
    T.assertNil(find(function(f)
      local label = f:GetText()
      return type(label)=="string" and label:find("Animations :", 1, true)
    end))
    T.assertNil(ns.GetDB().settings.reduceMotion)
    noErrors()
  end)
  T.it("switches themes from their tab without reloading or rebuilding the UI", function()
    local other = expectedTheme == "slate" and "legacy" or "slate"
    local state, revision = Core.state, Core.state.rev
    local reloads = frames.reloads
    local titleColor, noteColor = Theme.Colors.TEXT_TITLE, Theme.Colors.NOTE_BG
    local created = #frames.frames
    UI.setTab(UI.TAB_IDS.THEMES)
    UI.themeControls.preset.buttons[other == "slate" and 1 or 2]:RunScript("OnClick")
    T.assertEq(Theme.GetSelectedName(), other)
    T.assertEq(ns.GetDB().settings.theme, other)
    T.assertEq(Theme.GetName(), other)
    T.assertEq(Theme.Colors.TEXT_TITLE, titleColor)
    T.assertEq(Theme.Colors.NOTE_BG, noteColor)
    T.assertEq(UI.title._textColor[1], titleColor[1])
    T.assertEq(UI.sidebar._backdropColor[1], noteColor[1])
    T.assertEq(#frames.frames, created)
    T.assertEq(frames.reloads, reloads)
    T.assertEq(Core.state, state); T.assertEq(Core.state.rev, revision)
    ns.UI_Show(false); ns.UI_Show(true)
    T.assertEq(Theme.GetSelectedName(), other)
    T.assertFalse(Theme.SetName("unknown"))
    T.assertEq(Theme.GetSelectedName(), other)
    UI.themeControls.preset.buttons[expectedTheme == "slate" and 1 or 2]:RunScript("OnClick")
    T.assertEq(Theme.GetSelectedName(), expectedTheme)
    T.assertFalse(Theme.IsPending())
    UI.setTab(1)
    noErrors()
  end)
  T.it("loads the actual TOC and initializes all pages exactly once", function()
    T.assertNotNil(ns.Guard); T.assertNotNil(Core.PercentageHeal); T.assertNotNil(Core.PetPercentageHeal)
    T.assertEq(#UI.pages,11)
    local count=0
    for _,tab in ipairs(UI.tabs) do if tab:IsShown() then count=count+1 end end
    T.assertEq(count,6)
    local created=#frames.frames
    ns.UI_Init()
    T.assertEq(#frames.frames,created)
    noErrors()
  end)
  T.it("renders every class and switches all visible player and pet pages", function()
    for _,b in ipairs(UI.classButtons) do
      b:RunScript("OnClick")
      for _,tab in ipairs({1,3,5,6,7,8}) do
        UI.setTab(tab); T.assertTrue(UI.pages[tab]:IsShown())
        for i,p in ipairs(UI.pages) do if i~=tab then T.assertFalse(p:IsShown()) end end
      end
      T.assertEq(Core.state.classKey,b.classKey)
    end
    Core.SetPetEnabled(true)
    UI.setSidebarSection(2)
    for _,tab in ipairs({9,10,11}) do UI.setTab(tab); T.assertTrue(UI.pages[tab]:IsShown()) end
    UI.setSidebarSection(1); UI.setTab(1)
    noErrors()
  end)
  T.it("commits a numeric edit exactly once on Enter", function()
    Core.ResetToDefaults(); Core.SetHP(100,100)
    local original, calls=Core.SetHP,0
    Core.SetHP=function(...) calls=calls+1; return original(...) end
    UI.inputs.hpCur:SetFocus(); UI.inputs.hpCur:SetText("73")
    UI.inputs.hpCur:RunScript("OnEnterPressed")
    Core.SetHP=original
    T.assertEq(calls,1); T.assertEq(Core.state.hp,73)
    T.assertFalse(UI.inputs.hpCur:HasFocus())
  end)
  T.it("leaves text-edit undo shortcuts with the focused edit box", function()
    UI.inputs.hpCur:SetFocus()
    frames.ctrl=true; frames.mouseOver=UI.frame
    local depth=Core.GetUndoDepth()
    UI.frame:RunScript("OnKeyDown","z")
    T.assertTrue(UI.frame._propagate)
    T.assertEq(Core.GetUndoDepth(),depth)
    frames.ctrl=false; UI.inputs.hpCur:ClearFocus()
  end)
  T.it("keeps the integrated percentage-heal action operational", function()
    Core.SetHP(10,100)
    local value=assert(find(function(f)
      return f._kind=="EditBox" and f._parent and f._parent._parent==UI.ficheAfterRanged and f._parent:GetWidth()==120
    end))
    value:SetText("20")
    button("Pourcentage"):RunScript("OnClick")
    T.assertEq(Core.state.hp,30)
    noErrors()
  end)
  T.it("creates only the two surviving percentage controls", function()
    local percentages = {}
    for _, f in ipairs(frames.frames) do
      if f._kind == "Button" then
        T.assertNeq(f:GetText(), "Soins divins (75%)")
        T.assertNeq(f:GetText(), "Chirurgie (50%)")
        if f:GetText() == "Pourcentage" then percentages[#percentages + 1] = f end
      end
    end
    T.assertEq(#percentages, 2)
    T.assertEq(percentages[1]:GetWidth(), 440)
    T.assertEq(percentages[2]:GetWidth(), 380)
  end)
  T.it("keeps percentage input separate from commits and rejects invalid clicks", function()
    Core.ResetToDefaults(); Core.SetHP(70, 100)
    Core.SetPetEnabled(true); Core.SetPetHP(60, 100)
    for _, sheet in ipairs({ {1, 1, UI.inputs.actionValue, "PV : 57 / 100 (57%)"},
        {2, 9, UI.inputs.petActionVal, "PV familier : 47 / 100 (48%)"} }) do
      UI.setSidebarSection(sheet[1]); UI.setTab(sheet[2])
      local value, action = sheet[3], button("Pourcentage")
      local target = sheet[1] == 2 and Core.state.pet or Core.state
      local before, rev = target.hp, Core.state.rev
      value:SetFocus(); value:SetText("-12.5"); value:RunScript("OnEnterPressed")
      T.assertFalse(value:HasFocus())
      T.assertEq(target.hp, before); T.assertEq(Core.state.rev, rev)
      action:RunScript("OnClick")
      T.assertEq(target.hp, before - 12.5)
      T.assertEq(UI.hpText:GetText(), sheet[4])
      T.assertEq(UI.hpBar:GetValue(), (before - 12.5) / 100)
      T.assertEq(Core.state.rev, rev + 1)
      T.assertEq(Core.state.history[1].applied, 12.5)
      T.assertEq(Core.state.meter.dmg, 0)
      action:RunScript("OnEnter"); action:RunScript("OnLeave")
      local hp, count = target.hp, #Core.state.history
      rev = Core.state.rev
      local printer, messages = print, {}
      _G.print = function(message) messages[#messages + 1] = message end
      for _, invalid in ipairs({ "0", "0.5", "-101", "1e999", "abc" }) do
        value:SetText(invalid); action:RunScript("OnClick")
      end
      _G.print = printer
      T.assertEq(#messages, 5)
      T.assertTrue(messages[1]:find("-100", 1, true) ~= nil)
      T.assertEq(target.hp, hp); T.assertEq(Core.state.rev, rev)
      T.assertEq(#Core.state.history, count)
    end
    UI.setSidebarSection(1); UI.setTab(1)
    noErrors()
  end)
  T.it("accepts signed percentage damage and healing in player and pet fields", function()
    Core.ResetToDefaults(); Core.SetHP(70,100)
    local value=assert(find(function(f)
      return f._kind=="EditBox" and f._parent and f._parent._parent==UI.ficheAfterRanged and f._parent:GetWidth()==120
    end))
    T.assertFalse(value._callSetNumeric[1])
    value:SetText("-15"); button("Pourcentage"):RunScript("OnClick")
    T.assertEq(Core.state.hp,55)
    value:SetText("+15"); button("Pourcentage"):RunScript("OnClick")
    T.assertEq(Core.state.hp,70)
    Core.SetPetEnabled(true); Core.SetPetHP(60,200)
    UI.setSidebarSection(2); UI.setTab(9)
    local petButton=button("Pourcentage")
    local petValue=assert(find(function(f)
      return f._kind=="EditBox" and f:IsVisible() and f._parent and f._parent._parent
        and f._parent._parent._parent==petButton._parent._parent and f._parent:GetWidth()==80
    end))
    T.assertFalse(petValue._callSetNumeric[1])
    petValue:SetText("-15"); petButton:RunScript("OnClick")
    T.assertEq(Core.state.pet.hp,30)
    petValue:SetText("15"); petButton:RunScript("OnClick")
    T.assertEq(Core.state.pet.hp,60)
    T.assertEq(Core.state.hp,70)
    UI.setSidebarSection(1); UI.setTab(1)
    noErrors()
  end)
  T.it("creates, edits and copies grimoire entries through the real controls", function()
    UI.setTab(7); UI.openGrimoireEditor()
    T.assertTrue(UI.grimoireEditorOpen)
    -- Opening the editor focuses its title field.
    T.assertNotNil(frames.focus)
    frames.focus:SetText("Flamme de contrôle")
    UI.grimoireDamageHealingEdit:SetText("12-24")
    button("Enregistrer"):RunScript("OnClick")
    T.assertFalse(UI.grimoireEditorOpen)
    T.assertEq(#ns.Grimoire.GetTechniques(),1)
    button("Copier"):RunScript("OnClick")
    T.assertTrue(UI.grimoireCopyDialog:IsShown())
    UI.grimoireCopyDialog:Hide()
    button("Modifier"):RunScript("OnClick")
    frames.focus:SetText("Flamme révisée")
    button("Enregistrer"):RunScript("OnClick")
    T.assertEq(ns.Grimoire.GetTechniques()[1].title,"Flamme révisée")
    UI.openGrimoireIconPicker(nil,function() end)
    T.assertTrue(#UI.grimoireIconPicker.buttons>200)
    UI.grimoireIconPicker:Hide(); UI.setTab(1)
    noErrors()
  end)
  T.it("replaces Beledar and special cases with timed elixirs on both sheets", function()
    Core.ResetToDefaults(); Core.SetAttaque(10,20); Core.SetArmor(3,0)
    Core.SetPetEnabled(true); Core.SetPetAttaque(5,8); Core.SetPetArmor(2,0)
    UI.setSidebarSection(1); UI.setTab(UI.TAB_IDS.PLAYER_AFFIXES)
    local keys={CAMBUSE_ATTAQUE=true,CAMBUSE_PV=true,ELIXIR_PUISSANCE=true,ELIXIR_RESISTANCE=true}
    for _,buttons in ipairs({UI.affixButtons,UI.petAffixButtons}) do
      T.assertEq(#buttons,4)
      for _,b in ipairs(buttons) do T.assertTrue(keys[b._affixKey]) end
    end
    T.assertNil(find(function(f) return f._scKey or (f._affixKey and not keys[f._affixKey]) end))
    T.assertFalse(UI.affixNextTurnButton:IsEnabled())
    button("Cambuse : Attaque"):RunScript("OnClick")
    button("Élixir de puissance"):RunScript("OnClick")
    button("Élixir de résistance"):RunScript("OnClick")
    T.assertEq(Core.state.attaqueMelee,50); T.assertEq(Core.state.armor,9)
    T.assertNotNil(button("Élixir de puissance (3)"))
    UI.setSidebarSection(2); UI.setTab(UI.TAB_IDS.PET_AFFIXES)
    button("Élixir de puissance"):RunScript("OnClick")
    button("Élixir de résistance"):RunScript("OnClick")
    T.assertEq(Core.state.pet.attaqueMelee,35); T.assertEq(Core.state.pet.armor,8)
    for turns=2,1,-1 do
      button("Tour suivant"):RunScript("OnClick")
      T.assertEq(Core.state.affixTurns.ELIXIR_PUISSANCE,turns)
      T.assertEq(Core.state.pet.affixTurns.ELIXIR_RESISTANCE,turns)
      T.assertNotNil(button("Élixir de résistance ("..turns..")"))
    end
    button("Tour suivant"):RunScript("OnClick")
    T.assertEq(Core.state.attaqueMelee,20); T.assertEq(Core.state.armor,3)
    T.assertEq(Core.state.pet.attaqueMelee,5); T.assertEq(Core.state.pet.armor,2)
    T.assertFalse(UI.affixNextTurnButton:IsEnabled()); T.assertFalse(UI.petAffixNextTurnButton:IsEnabled())
    T.assertTrue(Core.state.affixes.CAMBUSE_ATTAQUE)
    UI.setSidebarSection(1); UI.setTab(1)
    noErrors()
  end)
  T.it("preserves the pet title across window reopen and profile refresh", function()
    Core.SetPetEnabled(true); Core.SetPetName("Compagnon")
    UI.setSidebarSection(2)
    ns.UI_Show(false); ns.UI_Show(true)
    T.assertEq(UI.title:GetText(),"Compagnon")
    UI.setSidebarSection(1)
  end)
  T.it("builds the target popup and displays authoritative health", function()
    mocks.units = {
      player={name="TestPlayer",realm="TestRealm",guid="Player-1-1",isPlayer=true},
      target={name="TargetPlayer",realm="TestRealm",guid="Player-1-2",isPlayer=true},
    }
    ns.TargetPopup.InjectState("TargetPlayer-TestRealm",Core.state)
    ns.TargetPopup:OnTargetChanged()
    T.assertTrue(_G.GrosOrteilTargetPopup:IsShown())
    T.assertEq(UI.hpBar:GetValue(),Core.state.hp/Core.state.maxHp)
    _G.GrosOrteilTargetPopup:Hide(); mocks.units=nil
    noErrors()
  end)
  T.it("cancels stale close animations when reopened, including direct Show", function()
    ns.UI_Show(false, true); T.assertTrue(UI.fadeOut:IsPlaying())
    ns.UI_Show(true); frames.finishAnimations()
    T.assertTrue(UI.frame:IsShown()); T.assertTrue(ns.GetDB().ui.shown)
    ns.UI_Show(false, true); UI.frame:Hide(); UI.frame:Show(); frames.finishAnimations()
    T.assertTrue(UI.frame:IsShown())
  end)
  T.it("keeps native animations active after migrating the removed motion preference", function()
    ns.UI_Show(false, true)
    T.assertTrue(UI.fadeOut:IsPlaying())
    frames.finishAnimations()
    T.assertFalse(UI.frame:IsShown())
    ns.UI_Show(true); UI.setTab(7)
    local opening = false
    for _,group in ipairs(frames.animations) do
      if group.region==UI.frame and group:IsPlaying() then opening=true end
    end
    T.assertTrue(opening)
    frames.finishAnimations()
    for _,group in ipairs(frames.animations) do
      if group.region==UI.frame or group.region==UI.pages[7] then T.assertFalse(group:IsPlaying()) end
    end
    T.assertTrue(UI.frame:IsShown()); T.assertTrue(UI.pages[7]:IsShown())
    UI.setTab(1)
  end)
  T.it("stops resizing when hidden and persists the complete anchor", function()
    local grip=assert(find(function(f)
      return f._parent==UI.frame and f._NormalTexture and tostring(f._NormalTexture:GetTexture()):find("SizeGrabber",1,true)
    end))
    grip:RunScript("OnMouseDown","LeftButton")
    T.assertNotNil(grip:GetScript("OnUpdate"))
    frames.cursorX=frames.cursorX+30; grip:RunScript("OnUpdate")
    UI.frame:Hide()
    T.assertNil(grip:GetScript("OnUpdate"))
    T.assertEq(ns.GetDB().ui.relativePoint,"BOTTOMLEFT")
    ns.UI_Show(true)
    local _,_,relativePoint=UI.frame:GetPoint(1)
    T.assertEq(relativePoint,"BOTTOMLEFT")
    ns.UI_ResetPosition(); T.assertEq(ns.GetDB().ui.relativePoint,"CENTER")
  end)
  T.it("fits the navigation and fixed control rows at minimum window size", function()
    UI.frame:SetSize(760,460); frames.layout()
    T.assertTrue(UI.content:GetWidth()>=500)
    T.assertTrue(UI.tabs[8]:GetBottom()>UI.resetBtn:GetTop())
    T.assertTrue(UI.inputs.hpCur:GetLeft()>=UI.content:GetLeft())
    T.assertTrue(UI.inputs.hpMax:GetRight()<=UI.content:GetRight())
    T.assertTrue(UI.distanceButton:GetRight()<UI.iconRegenRes:GetLeft())
    UI.frame:SetSize(940,580); frames.layout()
  end)
end)
T.describe("Raid panel combat boundaries",function()
  T.it("defers first creation until combat ends",function()
    frames.combat=true; frames.fire("PLAYER_REGEN_DISABLED")
    ns.RaidPanel.Show(); T.assertNil(_G.GrosOrteilRaidPanel)
    ns.RaidPanel.Hide()
    frames.combat=false; frames.fire("PLAYER_REGEN_ENABLED")
    T.assertNil(_G.GrosOrteilRaidPanel)
    frames.combat=true; frames.fire("PLAYER_REGEN_DISABLED")
    ns.RaidPanel.Toggle(); ns.RaidPanel.Toggle(); ns.RaidPanel.Toggle()
    T.assertNil(_G.GrosOrteilRaidPanel)
    frames.combat=false; frames.fire("PLAYER_REGEN_ENABLED"); frames.layout()
    T.assertTrue(_G.GrosOrteilRaidPanel:IsShown())
    noErrors()
  end)
  T.it("retains secure target attributes and defers view changes",function()
    local sec=assert(find(function(f) return f._attrs.type1=="target" end))
    T.assertEq(sec:GetAttribute("*type1"),"target")
    T.assertNotNil(sec:GetAttribute("unit"))
    T.assertNil(sec:GetScript("OnClick"))
    local sf=_G.GrosOrteilRaidPanelScroll
    local originalChild=sf._scrollChild
    local meter=assert(find(function(f) return f._view=="meter" end))
    frames.combat=true; frames.fire("PLAYER_REGEN_DISABLED")
    meter:RunScript("OnClick")
    T.assertEq(sf._scrollChild,originalChild)
    for _,name in ipairs(UISpecialFrames) do T.assertNeq(name,"GrosOrteilRaidPanel") end
    frames.combat=false; frames.fire("PLAYER_REGEN_ENABLED")
    T.assertNeq(sf._scrollChild,originalChild)
    assert(find(function(f) return f._view=="group" end)):RunScript("OnClick")
  end)
  T.it("handles combat beginning during a close animation",function()
    ns.RaidPanel.Hide()
    frames.combat=true; frames.fire("PLAYER_REGEN_DISABLED")
    frames.finishAnimations()
    T.assertTrue(_G.GrosOrteilRaidPanel:IsShown())
    ns.RaidPanel.Show() -- newest intent wins
    frames.combat=false; frames.fire("PLAYER_REGEN_ENABLED"); frames.finishAnimations()
    T.assertTrue(_G.GrosOrteilRaidPanel:IsShown())
    frames.combat=true; frames.fire("PLAYER_REGEN_DISABLED"); ns.RaidPanel.Hide()
    T.assertTrue(_G.GrosOrteilRaidPanel:IsShown())
    frames.combat=false; frames.fire("PLAYER_REGEN_ENABLED"); frames.finishAnimations()
    T.assertFalse(_G.GrosOrteilRaidPanel:IsShown())
  end)
  T.it("stops scale dragging before any protected mutation in combat",function()
    ns.RaidPanel.Show()
    local panel=_G.GrosOrteilRaidPanel
    local grip=assert(find(function(f)
      return f._parent==panel and f._NormalTexture and tostring(f._NormalTexture:GetTexture()):find("SizeGrabber",1,true)
    end))
    grip:RunScript("OnMouseDown","LeftButton")
    frames.combat=true
    grip:RunScript("OnUpdate")
    T.assertNil(grip:GetScript("OnUpdate"))
    frames.fire("PLAYER_REGEN_DISABLED")
    frames.combat=false; frames.fire("PLAYER_REGEN_ENABLED")
    ns.RaidPanel.Hide(); frames.finishAnimations()
  end)
end)
require("test_ui_refinements")(T,ns,frames)
T.describe("Runtime regressions",function()
  T.it("parses both meter counters through all shipped guards",function()
    ns.Comm:OnChatMsgAddon(ns.Comm.PREFIX,"METER_STATE:42:84","PARTY","Peer-TestRealm")
    local totals=ns.MeterSync.Get("Peer-TestRealm")
    T.assertEq(totals.dmg,42); T.assertEq(totals.heal,84)
    ns.MeterSync.Store("Peer-TestRealm",0/0,math.huge)
    totals=ns.MeterSync.Get("Peer-TestRealm")
    T.assertEq(totals.dmg,0); T.assertEq(totals.heal,0)
  end)
  T.it("passes the shipped in-game suite with the UI subscribed",function()
    local ok,pass,fail=ns.Tests.RunAll(false)
    T.assertTrue(ok,"packaged suite failed: "..tostring(fail)); T.assertTrue(pass>=60)
    noErrors()
  end)
  T.it("has no idle update loops after interactions settle",function()
    frames.finishAnimations()
    for _,f in ipairs(frames.frames) do T.assertNil(f:GetScript("OnUpdate"),f._name or f._kind) end
    noErrors()
  end)
end)
require("test_grimoire_editor")(T,ns,frames)
require("test_ui_refresh")(T,ns,frames)
require("test_ui_lifecycle")(T,ns,frames)
require("test_themes")(T,ns,frames)
local ok=T.run({verbose=true})
os.exit(ok and 0 or 1)
