---@diagnostic disable: undefined-global
local T = _G.T
local ns = _G.NS
local Shared = ns.Shared

T.describe("Shared.Round", function()
  T.it("rounds halves to nearest integer", function()
    T.assertEq(Shared.Round(0.5),  1)
    T.assertEq(Shared.Round(1.49), 1)
    T.assertEq(Shared.Round(1.5),  2)
    T.assertEq(Shared.Round(-0.5), -1)
    T.assertEq(Shared.Round(-1.5), -2)
  end)
  T.it("returns 0 for non-numeric input", function()
    T.assertEq(Shared.Round(nil),   0)
    T.assertEq(Shared.Round("foo"), 0)
  end)
end)

T.describe("Shared.RoundPct", function()
  T.it("converts fraction to integer percent", function()
    T.assertEq(Shared.RoundPct(0),     0)
    T.assertEq(Shared.RoundPct(0.5),   50)
    T.assertEq(Shared.RoundPct(0.999), 100)
    T.assertEq(Shared.RoundPct(1),     100)
    T.assertEq(Shared.RoundPct(0.123), 12)
  end)
end)

T.describe("Shared.GetKeysForIdx", function()
  T.it("maps indexes 1..5 to known keys", function()
    local r1, m1 = Shared.GetKeysForIdx(1); T.assertEq(r1, "res");  T.assertEq(m1, "maxRes")
    local r2, m2 = Shared.GetKeysForIdx(2); T.assertEq(r2, "res2"); T.assertEq(m2, "maxRes2")
    local r3, m3 = Shared.GetKeysForIdx(3); T.assertEq(r3, "res3"); T.assertEq(m3, "maxRes3")
    local r4, m4 = Shared.GetKeysForIdx(4); T.assertEq(r4, "res4"); T.assertEq(m4, "maxRes4")
    local r5, m5 = Shared.GetKeysForIdx(5); T.assertEq(r5, "auth"); T.assertEq(m5, "maxAuth")
  end)
  T.it("returns nil for out-of-range indexes", function()
    local r, m = Shared.GetKeysForIdx(0); T.assertNil(r); T.assertNil(m)
    r, m = Shared.GetKeysForIdx(99);      T.assertNil(r); T.assertNil(m)
  end)
end)

T.describe("Shared.GetResProfile", function()
  T.it("returns Warlock 3-resource profile", function()
    local p = Shared.GetResProfile({ classKey = "WARLOCK" })
    T.assertEq(#p, 3)
    T.assertEq(p[1].label, "Énergie gangrénée")
    T.assertEq(p[2].label, "Corruption")
    T.assertEq(p[3].label, "Fragments d'âme")
  end)
  T.it("returns single fallback for class without explicit profile", function()
    local p = Shared.GetResProfile({ classKey = "ROGUE" })
    T.assertEq(#p, 1)
    T.assertEq(p[1].label, "Énergie")
  end)
  T.it("returns generic Ressource for unknown class", function()
    local p = Shared.GetResProfile({ classKey = "UNKNOWN" })
    T.assertEq(#p, 1)
    T.assertEq(p[1].label, "Ressource")
  end)
  T.it("appends auth slot when pet authority is enabled", function()
    local s = { classKey = "MAGE", pet = { enabled = true, authorityEnabled = true } }
    local p = Shared.GetResProfile(s)
    -- Mage profile has 2 entries + auth.
    T.assertEq(#p, 3)
    T.assertEq(p[#p].idx, 5)
  end)
  T.it("does not append auth when pet disabled", function()
    local s = { classKey = "MAGE", pet = { enabled = false, authorityEnabled = true } }
    local p = Shared.GetResProfile(s)
    T.assertEq(#p, 2)
  end)
end)

T.describe("Shared.GetClassNameFr", function()
  T.it("returns localized name for known classes", function()
    T.assertEq(Shared.GetClassNameFr("MAGE"),    "Mage")
    T.assertEq(Shared.GetClassNameFr("WARLOCK"), "Démoniste")
    T.assertEq(Shared.GetClassNameFr("MEDIC"),   "Médecin")
  end)
  T.it("falls back gracefully for unknown / nil input", function()
    T.assertEq(Shared.GetClassNameFr(nil), "Inconnue")
    T.assertEq(Shared.GetClassNameFr(""),  "Inconnue")
    T.assertEq(Shared.GetClassNameFr("MADE_UP"), "MADE_UP")
  end)
end)
