---@diagnostic disable: undefined-global
local T, ns = _G.T, _G.NS
local Core, Comm = ns.Core, ns.Comm
local ranges = { "courte", "moyenne", "longue" }

local function reset()
  Core.ResetToDefaults()
  Core.SetAttaque(12, 40)
  Core.SetPetEnabled(true)
  Core.SetPetAttaque(8, 20)
end

local function assertRanges(state, short, medium, long)
  for i, expected in ipairs({ short, medium, long }) do
    T.assertEq(Core.GetRangedAttack(state, ranges[i]), expected, ranges[i])
  end
end

local function receive()
  return Comm:DeserializeState("STATE_DATA", Comm.SerializeState(Core.state), "RangedTester")
end

T.describe("Ranged attack profiles", function()
  T.it("inherits the general distance attack until each range is edited", function()
    reset()
    assertRanges(Core.state, 40, 40, 40)
    Core.SetRangedAttack("courte", 65)
    Core.SetRangedAttack("longue", 10)
    Core.SetAttaque(15, 48)
    assertRanges(Core.state, 65, 48, 10)
    T.assertEq(Core.state.attaqueMelee, 15)
    T.assertEq(Core.state.attaqueDistance, 48)
    Core.SetRangedAttack("courte", nil)
    assertRanges(Core.state, 48, 48, 10)
    T.assertNil(Core.state.attaqueDistanceCourte)
  end)

  T.it("keeps player and pet custom values independent", function()
    reset()
    Core.SetRangedAttack("courte", 65)
    Core.SetRangedAttack("moyenne", 25, true)
    Core.SetPetAttaque(9, 22)
    assertRanges(Core.state, 65, 40, 40)
    assertRanges(Core.state.pet, 22, 25, 22)
    Core.SetRangedAttack("moyenne", nil, true)
    assertRanges(Core.state.pet, 22, 22, 22)
  end)

  T.it("applies Cambuse and three-turn power bonuses to every range", function()
    reset()
    Core.SetRangedAttack("courte", 65)
    Core.SetRangedAttack("longue", 10)
    Core.ToggleAffix("CAMBUSE_ATTAQUE")
    Core.ToggleAffix("ELIXIR_PUISSANCE")
    assertRanges(Core.state, 105, 80, 50)
    Core.NextTurn(); Core.NextTurn()
    assertRanges(Core.state, 105, 80, 50)
    Core.NextTurn()
    assertRanges(Core.state, 75, 50, 20)
    Core.ToggleAffix("CAMBUSE_ATTAQUE")
    assertRanges(Core.state, 65, 40, 10)
  end)

  T.it("stores edited displayed values without making temporary bonuses permanent", function()
    reset()
    Core.ToggleAffix("ELIXIR_PUISSANCE")
    Core.TogglePetAffix("ELIXIR_PUISSANCE")
    Core.SetRangedAttack("courte", 85)
    Core.SetRangedAttack("longue", 15)
    Core.SetRangedAttack("moyenne", 75, true)
    assertRanges(Core.state, 85, 70, 15)
    assertRanges(Core.state.pet, 50, 75, 50)
    Core.NextTurn(); Core.NextTurn(); Core.NextTurn()
    assertRanges(Core.state, 55, 40, 0)
    assertRanges(Core.state.pet, 20, 45, 20)
    Core.ToggleAffix("ELIXIR_PUISSANCE")
    assertRanges(Core.state, 85, 70, 15)
  end)

  T.it("tracks Insanity tier changes and their removal on a class change", function()
    reset()
    Core.SetClassKey("SHADOWPRIEST")
    Core.SetRangedAttack("courte", 65)
    Core.SetResIndex(2, 11, 25)
    assertRanges(Core.state, 75, 50, 50)
    Core.SetResIndex(2, 18, 25)
    Core.ToggleAffix("ELIXIR_PUISSANCE")
    assertRanges(Core.state, 110, 85, 85)
    Core.SetRangedAttack("longue", 60)
    Core.SetClassKey("WARRIOR")
    assertRanges(Core.state, 95, 70, 45)
    Core.ToggleAffix("ELIXIR_PUISSANCE")
    assertRanges(Core.state, 65, 40, 15)
  end)

  T.it("does not truncate a custom range bonus when the general attack is capped", function()
    reset()
    Core.SetAttaque(12, 1e9)
    Core.SetRangedAttack("courte", 65)
    Core.ToggleAffix("ELIXIR_PUISSANCE")
    assertRanges(Core.state, 95, 1e9, 1e9)
    Core.NextTurn(); Core.NextTurn(); Core.NextTurn()
    assertRanges(Core.state, 65, 1e9, 1e9)
  end)

  T.it("rejects invalid inputs and treats unchanged edits as no-ops", function()
    reset()
    Core.SetRangedAttack("courte", 65)
    local rev = Core.state.rev
    for _, invalid in ipairs({ 0/0, math.huge, -math.huge, "123", {}, false }) do
      Core.SetRangedAttack("courte", invalid)
    end
    Core.SetRangedAttack("unknown", 12)
    Core.SetRangedAttack("courte", 65)
    Core.SetRangedAttack("moyenne", nil)
    T.assertEq(Core.state.rev, rev)
    assertRanges(Core.state, 65, 40, 40)
    Core.SetRangedAttack("courte", -3)
    Core.SetRangedAttack("longue", 2e9)
    assertRanges(Core.state, 0, 40, 1e9)
  end)

  T.it("handles malformed or old saved range values without invalid arithmetic", function()
    for _, invalid in ipairs({ 0/0, math.huge, -math.huge, {}, "abc" }) do
      assertRanges({ attaqueDistance = 34, attaqueDistanceCourte = invalid }, 34, 34, 34)
      assertRanges({ attaqueDistance = invalid }, 0, 0, 0)
    end
    assertRanges(nil, 0, 0, 0)
    assertRanges({ attaqueDistanceCourte = 5, insanityAtkApplied = 0/0,
      affixApplied = { bad = { attaqueDistance = math.huge } } }, 5, 0, 0)
  end)

  T.it("undoes custom edits and restores inheritance for player and pet", function()
    reset()
    Core.BreakUndoCoalesce()
    Core.SetRangedAttack("courte", 65)
    Core.SetRangedAttack("longue", 12, true)
    Core.Undo()
    assertRanges(Core.state, 65, 40, 40)
    assertRanges(Core.state.pet, 20, 20, 20)
    Core.Undo()
    assertRanges(Core.state, 40, 40, 40)
    assertRanges(Core.state.pet, 20, 20, 20)
    T.assertNil(Core.state.attaqueDistanceCourte)
    Core.Redo()
    Core.Redo()
    assertRanges(Core.state, 65, 40, 40)
    assertRanges(Core.state.pet, 20, 20, 12)
    Core.BreakUndoCoalesce()
    Core.SetRangedAttack("courte", nil)
    Core.Undo()
    assertRanges(Core.state, 65, 40, 40)
  end)

  T.it("undoes and redoes potion expiry without changing custom bases", function()
    reset()
    Core.SetRangedAttack("courte", 65)
    Core.SetRangedAttack("longue", 12, true)
    Core.ToggleAffix("ELIXIR_PUISSANCE")
    Core.TogglePetAffix("ELIXIR_PUISSANCE")
    Core.NextTurn(); Core.NextTurn()
    Core.BreakUndoCoalesce(); Core.NextTurn()
    assertRanges(Core.state, 65, 40, 40)
    Core.Undo()
    assertRanges(Core.state, 95, 70, 70)
    assertRanges(Core.state.pet, 50, 50, 42)
    Core.Redo()
    assertRanges(Core.state, 65, 40, 40)
    assertRanges(Core.state.pet, 20, 20, 12)
  end)

  T.it("retains custom ranges and temporary effects across saved-state reinitialization", function()
    reset()
    Core.SetRangedAttack("courte", 65)
    Core.SetRangedAttack("longue", 12, true)
    Core.ToggleAffix("ELIXIR_PUISSANCE")
    Core.TogglePetAffix("CAMBUSE_ATTAQUE")
    Core.NextTurn()
    ns.Core_Init()
    assertRanges(Core.state, 95, 70, 70)
    assertRanges(Core.state.pet, 30, 30, 22)
    T.assertEq(Core.state.affixTurns.ELIXIR_PUISSANCE, 2)
    Core.NextTurn(); Core.NextTurn()
    assertRanges(Core.state, 65, 40, 40)
  end)
end)

T.describe("Ranged attack sharing", function()
  T.it("shares effective player and pet values without applying temporary bonuses twice", function()
    reset()
    Core.SetClassKey("SHADOWPRIEST")
    Core.SetRangedAttack("courte", 65)
    Core.SetRangedAttack("longue", 12, true)
    Core.SetResIndex(2, 18, 25)
    Core.ToggleAffix("ELIXIR_PUISSANCE")
    Core.TogglePetAffix("CAMBUSE_ATTAQUE")
    local peer = receive()
    assertRanges(peer, 110, 85, 85)
    assertRanges(peer.pet, 30, 30, 22)
    T.assertEq(peer.attaqueDistanceCourte, 110)
    T.assertEq(peer.attaqueDistance, 85)
    T.assertNil(peer.affixApplied)
    T.assertNil(peer.insanityAtkApplied)
    Core.NextTurn(); Core.NextTurn(); Core.NextTurn()
    assertRanges(receive(), 80, 55, 55)
  end)

  T.it("accepts old peer payloads that contain only the general distance value", function()
    local serializer = LibStub("AceSerializer-3.0")
    local payload = serializer:Serialize({ hp = 40, maxHp = 50,
      attaqueDistance = 48, pet = { enabled = true, attaqueDistance = 23 } })
    local peer = Comm:DeserializeState("STATE_DATA", payload, "OldRangedTester")
    assertRanges(peer, 48, 48, 48)
    assertRanges(peer.pet, 23, 23, 23)
    T.assertEq(peer.attaqueDistance, 48)
  end)
end)
