---@diagnostic disable: undefined-global
local T = _G.T
local ns = _G.NS
local Popup = ns.TargetPopup
local h = Popup._test  -- helpers exposed for tests; see GrosOrteil_TargetPopup.lua

T.describe("TargetPopup name normalization", function()
  T.it("normalizeName lowercases and strips whitespace", function()
    T.assertEq(h.normalizeName("  Foo Bar "), "foobar")
    T.assertEq(h.normalizeName("FOO"), "foo")
    T.assertNil(h.normalizeName(""))
    T.assertNil(h.normalizeName("   "))
    T.assertNil(h.normalizeName(nil))
    T.assertNil(h.normalizeName(42))
  end)
  T.it("splitNameRealm splits on hyphen", function()
    local short, realm = h.splitNameRealm("Foo-Realm")
    T.assertEq(short, "foo")
    T.assertEq(realm, "realm")
    short, realm = h.splitNameRealm("Foo")
    T.assertEq(short, "foo")
    T.assertNil(realm)
  end)
  T.it("toCacheKey strips realm so Foo and Foo-Realm share cache", function()
    T.assertEq(h.toCacheKey("Foo"), "foo")
    T.assertEq(h.toCacheKey("Foo-Realm"), "foo")
    T.assertEq(h.toCacheKey("Foo-OtherRealm"), "foo")
  end)
  T.it("namesMatch treats missing realm as wildcard", function()
    T.assertTrue(h.namesMatch("Foo", "Foo-Realm"))
    T.assertTrue(h.namesMatch("Foo-Realm", "Foo"))
    T.assertTrue(h.namesMatch("Foo-Realm", "Foo-Realm"))
    T.assertFalse(h.namesMatch("Foo-RealmA", "Foo-RealmB"))
    T.assertFalse(h.namesMatch("Foo", "Bar"))
    T.assertFalse(h.namesMatch(nil, "Foo"))
  end)
  T.it("baseCharacterName returns short name without realm", function()
    T.assertEq(h.baseCharacterName("Foo-Realm"), "Foo")
    T.assertEq(h.baseCharacterName("Foo"), "Foo")
    T.assertEq(h.baseCharacterName(""), "Inconnu")
    T.assertEq(h.baseCharacterName(nil), "Inconnu")
  end)
end)

T.describe("TargetPopup color stripping", function()
  T.it("stripColorCodes removes |cFFRRGGBB and |r escapes", function()
    T.assertEq(h.stripColorCodes("|cFF00FF00Hello|r"), "Hello")
    T.assertEq(h.stripColorCodes("plain"), "plain")
    T.assertEq(h.stripColorCodes("  spaced  "), "spaced")
    T.assertNil(h.stripColorCodes(""))
    T.assertNil(h.stripColorCodes(nil))
  end)
end)

T.describe("TargetPopup owner-tooltip parser", function()
  T.it("matches English '<X's Pet>'", function()
    T.assertEq(h.extractOwnerNameFromTooltipText("<Lucas's Pet>"), "Lucas")
  end)
  T.it("matches French '<Pet de X>'", function()
    T.assertEq(h.extractOwnerNameFromTooltipText("<Pet de Lucas>"), "Lucas")
  end)
  T.it("matches French 'Familier de X'", function()
    T.assertEq(h.extractOwnerNameFromTooltipText("Familier de Lucas"), "Lucas")
  end)
  T.it("matches French 'Compagnon de X'", function()
    T.assertEq(h.extractOwnerNameFromTooltipText("Compagnon de Lucas"), "Lucas")
  end)
  T.it("strips color codes before matching", function()
    T.assertEq(h.extractOwnerNameFromTooltipText("|cFFFFFFFF<Pet de Lucas>|r"), "Lucas")
  end)
  T.it("returns nil for unrecognized text", function()
    T.assertNil(h.extractOwnerNameFromTooltipText("just some random text"))
    T.assertNil(h.extractOwnerNameFromTooltipText(""))
    T.assertNil(h.extractOwnerNameFromTooltipText(nil))
  end)
end)

T.describe("TargetPopup state cache", function()
  T.it("setCached + getCached round-trip", function()
    -- Reset cache: stash + restore.
    local saved = {}
    for k, v in pairs(h.cache) do saved[k] = v; h.cache[k] = nil end
    h.setCached("foo", { hp = 10 })
    local got = h.getCached("foo")
    T.assertNotNil(got)
    T.assertEq(got.hp, 10)
    -- Restore.
    for k in pairs(h.cache) do h.cache[k] = nil end
    for k, v in pairs(saved) do h.cache[k] = v end
  end)
  T.it("getCached returns nil for missing key", function()
    T.assertNil(h.getCached("never-set-this-key"))
  end)
end)
