-- Registered by run_ui.lua after the actual addon and UI have been loaded.
return function(T, ns, frames)
  local UI, Core, Grimoire = ns.UI, ns.Core, ns.Grimoire

  local function button(text)
    for _, frame in ipairs(frames.frames) do
      if frame._kind == "Button" and frame:IsVisible() and frame:GetText() == text then return frame end
    end
    error("button missing: " .. text)
  end

  local function open(description)
    Core.ResetToDefaults()
    ns.UI_Show(true)
    UI.setSidebarSection(1)
    UI.setTab(UI.TAB_IDS.PLAYER_GRIMOIRE or 7)
    local technique = assert(Grimoire.CreateTechnique({
      title = "Flamme orange", description = description or "Une flamme orange dans la nuit.",
      damageHealing = 12, damageHealingMax = 24,
    }))
    UI.openGrimoireEditor(technique.id)
    frames.layout()
    return technique.id, UI.grimoireTitleEdit, UI.grimoireDescriptionEdit
  end

  T.describe("Grimoire native text editing", function()
    T.it("replaces only the selected words and preserves edits across refresh and focus changes", function()
      local id, title, description = open()
      for _, edit in ipairs({ title, description, UI.grimoireDamageHealingEdit }) do
        T.assertTrue(edit._callEnableMouse[1])
        T.assertFalse(edit._callSetPropagateMouseClicks[1])
      end
      title:HighlightText(7, 13)
      UI.refreshGrimoire(Core.state)
      title:Insert("bleue")
      T.assertEq(title:GetText(), "Flamme bleue")

      description:SetFocus()
      description:HighlightText(11, 17)
      Core.SetHP(61, 100)
      UI.refreshGrimoire(Core.state)
      description:Insert("bleue")
      T.assertEq(description:GetText(), "Une flamme bleue dans la nuit.")
      description:SetCursorPosition(10)
      title:SetFocus()
      description:SetFocus()
      description:Insert(" vive")
      T.assertEq(description:GetText(), "Une flamme vive bleue dans la nuit.")

      local damage = UI.grimoireDamageHealingEdit
      damage:SetFocus()
      damage:HighlightText(0, 2)
      damage:Insert("18")
      title:SetFocus()
      -- Unrelated selectors used to restore the saved damage text on blur.
      button("Illimité"):RunScript("OnClick")
      UI.refreshGrimoire(Core.state)
      T.assertEq(damage:GetText(), "18-24")
      button("Enregistrer"):RunScript("OnClick")
      local saved = Grimoire.GetTechniqueById(id)
      T.assertEq(saved.title, "Flamme bleue")
      T.assertEq(saved.description, "Une flamme vive bleue dans la nuit.")
      T.assertEq(saved.damageHealing, 18)
      T.assertEq(saved.damageHealingMax, 24)
      T.assertFalse(UI.grimoireEditorOpen)
    end)

    T.it("preserves unsaved cost and use counts after selector changes and validation errors", function()
      local id, title = open()
      Core.SetClassKey("MAGE")
      local costSelect = button("Aucun")
      costSelect:RunScript("OnClick")
      local amount, uses = UI.grimoireCostAmountEdit, UI.grimoireUsesEdit
      amount:SetFocus()
      amount:SetText("19")
      title:SetFocus()
      Core.SetHP(61, 100)
      UI.refreshGrimoire(Core.state)
      T.assertEq(amount:GetText(), "19")

      button("Illimité"):RunScript("OnClick")
      T.assertEq(amount:GetText(), "19")
      uses:SetFocus()
      uses:SetText("5")
      title:SetFocus()
      costSelect:RunScript("OnClick")
      UI.refreshGrimoire(Core.state)
      T.assertEq(amount:GetText(), "19")
      T.assertEq(uses:GetText(), "5")

      amount:SetText("")
      title:SetFocus()
      UI.refreshGrimoire(Core.state)
      T.assertEq(amount:GetText(), "")
      button("Enregistrer"):RunScript("OnClick")
      T.assertTrue(UI.grimoireEditorOpen)
      T.assertEq(uses:GetText(), "5")
      amount:SetText("19")
      button("Enregistrer"):RunScript("OnClick")
      local saved = Grimoire.GetTechniqueById(id)
      T.assertEq(saved.cost.amount, 19)
      T.assertEq(saved.usesPerMission, 5)
      T.assertFalse(UI.grimoireEditorOpen)
    end)

    T.it("keeps text undo and redo with the description instead of changing character history", function()
      local _, _, description = open()
      description:SetFocus()
      frames.ctrl, frames.mouseOver = true, UI.frame
      local undoDepth = Core.GetUndoDepth()
      for _, key in ipairs({ "z", "y" }) do
        UI.frame:RunScript("OnKeyDown", key)
        T.assertTrue(UI.frame._propagate)
        T.assertEq(Core.GetUndoDepth(), undoDepth)
      end
      frames.ctrl, frames.mouseOver = false, nil
      button("Annuler"):RunScript("OnClick")
    end)

    T.it("scrolls to the caret and bounds the editable hit area to the visible description", function()
      local _, _, description = open(string.rep("La flamme reste visible pendant trois tours.\n", 90))
      description:SetFocus()
      local scroll = description._scroll
      local range = scroll:GetVerticalScrollRange()
      T.assertTrue(range > 200)
      T.assertEq(scroll:GetVerticalScroll(), 0)
      description:RunScript("OnCursorChanged", 0, -210, 1, 12)
      T.assertEq(scroll:GetVerticalScroll(), 222 - scroll:GetHeight())
      T.assertEq(description._callSetHitRectInsets[3], scroll:GetVerticalScroll())
      T.assertEq(description._callSetHitRectInsets[4],
        description:GetHeight() - scroll:GetVerticalScroll() - scroll:GetHeight())
      description:RunScript("OnCursorChanged", 0, -4, 1, 12)
      T.assertEq(scroll:GetVerticalScroll(), 4)
      description:RunScript("OnMouseWheel", -10000)
      T.assertEq(scroll:GetVerticalScroll(), range)
      T.assertEq(description._callSetHitRectInsets[4], 0)
      description:RunScript("OnMouseWheel", 10000)
      T.assertEq(scroll:GetVerticalScroll(), 0)
      description:RunScript("OnCursorChanged", 0, -100000, 1, 12)
      T.assertEq(scroll:GetVerticalScroll(), range)
      description:SetText("Court")
      frames.layout()
      T.assertEq(scroll:GetVerticalScroll(), 0)
      T.assertEq(description._callSetHitRectInsets[3], 0)
      T.assertEq(description._callSetHitRectInsets[4], 0)
      button("Annuler"):RunScript("OnClick")
    end)

    T.it("opens another technique at its start and keeps select-all confined to manual copy", function()
      local id, title, description = open()
      description:SetFocus()
      description:SetText(string.rep("Une autre ligne.\n", 100))
      frames.layout()
      description:RunScript("OnMouseWheel", -10000)
      button("Annuler"):RunScript("OnClick")
      UI.openGrimoireEditor(id)
      T.assertEq(description:GetCursorPosition(), 0)
      T.assertEq(description._scroll:GetVerticalScroll(), 0)
      title:Insert("Petite ")
      T.assertEq(title:GetText(), "Petite Flamme orange")
      button("Annuler"):RunScript("OnClick")
      button("Copier"):RunScript("OnClick")
      local copy = UI.grimoireCopyDialog.editBox
      local text = Grimoire.FormatTechniqueForCopy(Grimoire.GetTechniqueById(id))
      T.assertEq(copy:GetText(), text)
      T.assertEq(copy._callHighlightText[1], 0)
      T.assertEq(copy._callHighlightText[2], -1)
      copy:Insert("accidental typing")
      T.assertEq(copy:GetText(), text)
      UI.grimoireCopyDialog:Hide()
      UI.setTab(1)
    end)
    T.it("grows for newlines and wrapping, scrolls through the viewport, and focuses blank space", function()
      local _, _, description = open(string.rep("x\n", 90))
      local scroll = description._scroll
      T.assertTrue(scroll:GetVerticalScrollRange() > 800, "short lines still need their full height")
      scroll:RunScript("OnMouseWheel", -10000)
      T.assertEq(scroll:GetVerticalScroll(), scroll:GetVerticalScrollRange())
      scroll:SetVerticalScroll(120) -- the template scrollbar uses this same path
      T.assertEq(description._callSetHitRectInsets[3], 120)
      description:SetText(string.rep("Un long paragraphe sans saut de ligne. ", 90))
      frames.layout()
      local w, h = UI.frame:GetWidth(), UI.frame:GetHeight()
      UI.frame:SetSize(1180, 700); frames.layout()
      local wideHeight = description:GetHeight()
      UI.frame:SetSize(760, 460); frames.layout()
      T.assertTrue(description:GetHeight() > wideHeight, "narrower text must create more scrollable lines")
      T.assertTrue(scroll:GetHeight() >= 180)
      description:SetText("Court"); frames.layout()
      T.assertEq(scroll:GetVerticalScroll(), 0)
      description:ClearFocus()
      scroll:RunScript("OnMouseUp", "LeftButton")
      T.assertTrue(description:HasFocus())
      T.assertEq(description:GetCursorPosition(), #description:GetText())
      description:Insert(" et lisible")
      T.assertEq(description:GetText(), "Court et lisible")
      button("Annuler"):RunScript("OnClick")
      UI.frame:SetSize(w, h); frames.layout()
    end)
    T.it("fits the complete description without truncation or overlapping metadata", function()
      local text = string.rep("Une longue description dans le grimoire.\n", 12)
      local id = open(text)
      button("Enregistrer"):RunScript("OnClick")
      frames.layout()
      local card
      for _, row in ipairs(UI.grimoireRows) do if row._techniqueId == id then card = row end end
      T.assertNotNil(card)
      T.assertEq(card.desc:GetText(), text)
      T.assertTrue(not card.desc._callSetMaxLines or card.desc._callSetMaxLines[1] == 0)
      T.assertTrue(card.desc:GetHeight() >= card.desc:GetStringHeight())
      T.assertTrue(card.desc:GetBottom() > card.meta:GetTop())
      T.assertTrue(card.meta:GetBottom() > card:GetBottom())
      T.assertEq(Grimoire.GetTechniqueById(id).description, text)
      UI.openGrimoireEditor(id)
      T.assertEq(UI.grimoireDescriptionEdit:GetText(), text)
      button("Annuler"):RunScript("OnClick")
    end)
    T.it("restacks variable-height cards after edits, reordering and deletion and clamps list scrolling", function()
      local id = open("Court")
      button("Annuler"):RunScript("OnClick")
      local second = Grimoire.CreateTechnique({title="Autre", description="Court aussi"})
      frames.layout()
      local firstRow, secondRow = UI.grimoireRows[1], UI.grimoireRows[2]
      local child = firstRow:GetParent()
      local scroll = child:GetParent()
      local shortHeight = firstRow:GetHeight()
      local measures, measure = 0, firstRow.desc.GetStringHeight
      firstRow.desc.GetStringHeight = function(self) measures = measures + 1; return measure(self) end
      Core.SetHP(61, 100)
      UI.refreshGrimoire(Core.state)
      T.assertEq(measures, 0, "unchanged text and width must not be measured again")
      Grimoire.UpdateTechnique(id, {description=string.rep("Une ligne\n", 100)})
      T.assertTrue(measures > 0)
      firstRow.desc.GetStringHeight = measure
      frames.layout()
      T.assertTrue(firstRow:GetHeight() > shortHeight + 900)
      T.assertNear(firstRow:GetBottom() - secondRow:GetTop(), 8)
      T.assertNear(child:GetHeight(), firstRow:GetHeight() + 8 + secondRow:GetHeight())
      scroll:SetVerticalScroll(scroll:GetVerticalScrollRange())
      Grimoire.UpdateTechnique(id, {description="Court"}); frames.layout()
      T.assertEq(firstRow:GetHeight(), shortHeight)
      T.assertEq(scroll:GetVerticalScroll(), scroll:GetVerticalScrollRange())
      Grimoire.MoveTechnique(second.id, -1); frames.layout()
      T.assertEq(firstRow._techniqueId, second.id)
      T.assertNear(firstRow:GetBottom() - secondRow:GetTop(), 8)
      Grimoire.DeleteTechnique(id); frames.layout()
      T.assertFalse(secondRow:IsShown())
      T.assertEq(child:GetHeight(), firstRow:GetHeight())
      Grimoire.DeleteTechnique(second.id); frames.layout()
      T.assertFalse(firstRow:IsShown())
      T.assertEq(scroll:GetVerticalScroll(), 0)
    end)
    T.it("remeasures wrapped titles, descriptions and metadata when the window changes width", function()
      local id = open(string.rep("Un paragraphe qui doit rester entièrement lisible. ", 30))
      button("Annuler"):RunScript("OnClick")
      Grimoire.UpdateTechnique(id, {title=string.rep("Un titre détaillé ", 12),
        cost={classKey="MAGE", resourceIdx=1, amount=99999}})
      local row = UI.grimoireRows[1]
      local w, h = UI.frame:GetWidth(), UI.frame:GetHeight()
      UI.frame:SetSize(1180, 700); frames.layout()
      local wide = row:GetHeight()
      UI.setTab(1)
      UI.frame:SetSize(760, 460); frames.layout()
      UI.setTab(UI.TAB_IDS.PLAYER_GRIMOIRE); frames.layout()
      T.assertTrue(row:GetHeight() > wide)
      T.assertTrue(row.title:GetBottom() > row.desc:GetTop())
      T.assertTrue(row.desc:GetBottom() > row.meta:GetTop())
      for _, text in ipairs({row.title, row.desc, row.meta}) do
        T.assertTrue(text:GetHeight() >= text:GetStringHeight())
      end
      T.assertTrue(row.meta:GetBottom() > row:GetBottom())
      UI.frame:SetSize(w, h); frames.layout()
    end)
  end)
end
